# Generated by Django 5.1.6 on 2025-02-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_device_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='device',
            name='shortname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
